services:
  ai-resume-analyzer:
    build:
      context: .
    container_name: ai-resume-analyzer
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
  ai-resume-analyzer-docs:
    image: squidfunk/mkdocs-material:latest
    container_name: ai-resume-analyzer-docs
    volumes:
      - ./mkdocs:/docs
    ports:
      - "8000:8000"
networks:
  resume_analyzer:
    name: resume_analyzer