services:
  ai-resume-analyzer:
    build:
      context: .
    container_name: ai-resume-analyzer
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    develop:
      # Create a `watch` configuration to update the app
      #
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

  ai-resume-analyzer-docs:
    image: squidfunk/mkdocs-material:latest
    container_name: ai-resume-analyzer-docs
    volumes:
      - ./mkdocs:/docs
    ports:
      - "8000:8000"

networks:
  resume_analyzer:
    name: resume_analyzer