---
    name: Deploy MkDocs to GitHub Pages

    on:
      push:
        branches:
          - main

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.11"

          - name: Install UV
            run: |
              curl -LsSf https://astral.sh/uv/install.sh | sh

          - name: Deploy to GitHub Pages
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: uv run mkdocs gh-deploy --config-file mkdocs/mkdocs.yml --force
